language: node_js
node_js:
  - "14.18.3"
cache:
  directories:
  - node_modules
script:
  - cd userscript/ && npm install && npm run build
after_failure: cat /home/travis/.npm/_logs/*-debug.log
warnings_are_errors: false
env:
  CI=false
